"""Add more size for password_hash

Revision ID: 30b2cbb01c8b
Revises: b364ea42fc33
Create Date: 2025-11-10 17:45:52.890881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b2cbb01c8b'
down_revision: Union[str, Sequence[str], None] = 'b364ea42fc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Usuario', 'password_hash',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Usuario', 'password_hash',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
