"""Creacion inicial del esquema de asistencia

Revision ID: 3e340546a4d2
Revises: 
Create Date: 2025-10-27 21:57:02.467137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e340546a4d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rfc_uid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rfc_uid')
    )
    op.create_table('Horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.VARCHAR(length=10), nullable=False),
    sa.Column('hora_inicio', sa.TIME(), nullable=False),
    sa.Column('hora_fin', sa.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.VARCHAR(length=50), nullable=False),
    sa.Column('grupo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ClaseProgramada',
    sa.Column('id_clase', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['Asignatura.id'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['Horario.id'], ),
    sa.PrimaryKeyConstraint('id_clase', 'id_horario')
    )
    op.create_table('Inscripcion',
    sa.Column('id_clase', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['Asignatura.id'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Estudiante.id'], ),
    sa.PrimaryKeyConstraint('id_clase', 'id_estudiante')
    )
    op.create_table('SesionDeClase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('hora_fin', sa.TIMESTAMP(), nullable=True),
    sa.Column('estado', sa.Enum('EnProgreso', 'Cerrada', name='estadosesion'), nullable=False),
    sa.Column('id_clase', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase', 'id_horario'], ['ClaseProgramada.id_clase', 'ClaseProgramada.id_horario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RegistroAsistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.TIMESTAMP(), nullable=True),
    sa.Column('hora_salida', sa.TIMESTAMP(), nullable=True),
    sa.Column('estado_asistencia', sa.Enum('Presente', 'Ausente', 'Tarde', name='estadoasistencia'), nullable=False),
    sa.Column('id_sesion_clase', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_sesion_clase'], ['SesionDeClase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RegistroAsistencia')
    op.drop_table('SesionDeClase')
    op.drop_table('Inscripcion')
    op.drop_table('ClaseProgramada')
    op.drop_table('Asignatura')
    op.drop_table('Usuario')
    op.drop_table('Horario')
    op.drop_table('Estudiante')
    # ### end Alembic commands ###
