"""Agregar columna tema a SesionDeClase

Revision ID: b364ea42fc33
Revises: 3e340546a4d2
Create Date: 2025-11-08 19:02:03.997609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b364ea42fc33'
down_revision: Union[str, Sequence[str], None] = '3e340546a4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SesionDeClase', sa.Column('tema', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SesionDeClase', 'tema')
    # ### end Alembic commands ###
